{
 "title": "Sistema de monitoreo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de disco (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sre_disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Idle (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sre_cpu_idle_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memoria disponible (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sre_memory_available_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}